all: mandelbrot.o mandelDisplay.o mandelDraw.o

mandelbrot.o:
	gcc -g -o mandelbrot mandelbrot-bprude2.c

mandelDisplay.o:
	gcc -g -o mandelDisplay mandelCalc-bprude2.c

mandelDraw.o:
	gcc -g -o mandelDraw mandelDisplay-bprude2.c